[project]
name = "yt-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "beautifulsoup4>=4.14.3",
  "google-api-python-client>=2.187.0",
  "ipykernel>=7.1.0",
  "networkx>=3.6.1",
  "notebook>=7.5.1",
  "pandas>=2.3.3",
  "pandas-gbq>=0.33.0",
  "pendulum>=3.1.0",
  "python-dotenv>=1.2.1",
  "tqdm>=4.67.1",
  "validators>=0.35.0",
]
